version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: keyloop-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:7
    container_name: keyloop-mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: document-viewer
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo_data:
